### ISSUE TITLE
While running inference on custom dataset getting KeyError: 0

### ISSUE THREAD

**Issue by ranjeetds** [aravindpai/How-to-build-own-text-summarizer-using-deep-learning#3]
While running inference on custom dataset getting KeyError: 0

Error log ->

> ---------------------------------------------------------------------------

> KeyError                                  Traceback (most recent call last)

> <ipython-input-37-695d86022aed> in <module>()

> ----> 1 decode_sequence(x_tr[i].reshape(1,max_text_len))

> <ipython-input-36-e96ad99a2d80> in decode_sequence(input_seq)

>      19         sampled_token_index = np.argmax(output_tokens[0, -1, :])

     

> 20         print(sampled_token_index)

> ---> 21         sampled_token = reverse_target_word_index[sampled_token_index]

     

> 22 

     

> 23         if(sampled_token!='eostok'):

> KeyError: 0

**Comment by qiuhuiGithub** [comment]
Hi, I guess that in the inference stage, we should ignore the first two index, which represent "padding" and "sostok".  so we can change the code like this:
`sampled_token_index = np.argmax(output_tokens[0, -1, 2:]) + 2`
Hope this can help you.
